### ISSUE TITLE
Installation fails with "Waiting for database to be ready..."

### ISSUE THREAD

**Issue by vins13pattar** [larasurf/larasurf#1]
Every time I tried to install it fails with "Waiting for database to be ready..." even-though MySQL image is pulled and build successfully. Unable to figure out the issue. Please help.
<img width="729" alt="Screenshot 2022-04-01 at 1 06 46 PM" src="https://user-images.githubusercontent.com/333259/161217767-a6a11f8e-5b3c-45e8-bc8c-15770479c6c8.png">

**Comment by bricehartmann** [comment]
Thanks for creating an issue!

For context, are you attempting to generate a project on WSL2 or macOS?

For reasons I'm not sure of yet, curl is failing to connect to the database container on the specified port of localhost after 60 seconds (20 tries with 3 second wait).

Since you've created this issue I've improved the logging of the project generation process as well as increased the timeout for connecting to the database to 3 minutes (60 tries) just in case.

Can you please try to generate your project again and if it fails again attach the file `larasurf.generate.log` in a comment here?

Heads up that the project generation command output will be minimal as most everything is now logged to the aforementioned file.

**Comment by vins13pattar** [comment]
Hi,
Thank you for the response.

I am on macOS.

On the 30th ping, the Database responded and migrations happened but this time it failed because of something else!! I have attached the larasurf.generate.log file to this comment. Please help how to get it fixed. Thank you in advance.

[larasurf.generate.log](https://github.com/larasurf/larasurf/files/8426836/larasurf.generate.log)
.

**Comment by bricehartmann** [comment]
Thank you for the information, the log file, and your patience.

I am happy the database responded this time around. I've identified the issue using the log file you attached and have made changes to resolve the bug.

We are very close as it failed at the very end of the process this time.

When you are able, please try to generate your project from scratch once more and let me know how it goes.

Thanks!

**Comment by vins13pattar** [comment]
@bricehartmann After project creation failed, I did run the build command manually and surf up and it worked! Thank you for the response and time given to look into the issue.
